# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-database-postgres
accountname: radio-aktywne
databasename: obsidian
description: Users identity database 👤
docs: true
docsurl: https://radio-aktywne.github.io/obsidian
envprefix: OBSIDIAN
imagename: databases/obsidian
port: 20110
registry: true
releases: true
reponame: obsidian
repourl: https://github.com/radio-aktywne/obsidian
